Saiyyed
learning-automation/AutomationRepo pull request #30
Opened 2022-12-22 09:55 UTC by ziyaulhuque

2022-12-22 09:58 UTC, ziyaulhuque commented
Changes are done

2022-12-22 10:19 UTC, JPrathmesh commented on src/test/java/pageObjects/ForgetLoginInfoPage.java
> -    @FindBy(xpath = "//*[@id=\"rightPanel\"]/p")
Remove the \ (slash) from xpath

2022-12-22 10:20 UTC, JPrathmesh commented on src/test/java/pageObjects/ForgetLoginInfoPage.java
>      public void firstName(String first_name) {
use enter word on creating  method

2022-12-22 10:22 UTC, JPrathmesh requested changes
Changes Requested

2022-12-22 13:29 UTC, ziyaulhuque commented
Final changes are done from saiyyed in forgetinfopage.

2022-12-22 16:51 UTC, JPrathmesh approved these changes

2022-12-23 03:41 UTC, JPrathmesh approved these changes

2022-12-23 03:42 UTC, learning-automation approved these changes

2022-12-23 03:42 UTC, merged